finished homework10
javascript149/shorenaBakradze pull request #6
Opened 2023-10-07 16:54 UTC by shorenabakradze

2023-10-09 20:53 UTC, Michael-Malania requested changes
გადახედე კომენტარს

2023-10-09 20:53 UTC, Michael-Malania commented on lesson10/login.html
> +        <form id="loginForm" onsubmit="return loginForm();">
form-ის ტეგში გაქ ჩასმული დეითა მაგრამ არასწორად ხდება მასზე მუშაობა რახან ეს მონაცემები არ მუშავდება და ბაზაში არ ინახება, შესაბამისად არც სისტემაში შესვლის გვერდი იმუშავებს

2023-10-09 20:53 UTC, Michael-Malania commented on lesson10/login.html
> +        <form id="loginForm" onsubmit="return loginForm();">
form-ის ტეგში გაქ ჩასმული დეითა მაგრამ არასწორად ხდება მასზე მუშაობა რახან ეს მონაცემები არ მუშავდება და ბაზაში არ ინახება, შესაბამისად არც სისტემაში შესვლის გვერდი იმუშავებს

2023-10-10 18:09 UTC, shorenabakradze reviewed
შევასწორე, შეცდომას აღარ წერს, გადახედეთ სჭირდება რამის დამატება ამ შეცვლა.

2023-10-10 18:10 UTC, shorenabakradze commented
შევასწორე, შეცდომას აღარ წერს, გადახედეთ სჭირდება რამის დამატება ამ შეცვლა?

2024-01-15 14:29 UTC, merged